load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "gm",
    hdrs = ["ground_truth_package.h",
            "measurement_package.h"],
    visibility = [
	"//main:__pkg__",
	"//algorithims:__pkg__",	
	],
)
